services:
  authservice:
    image: socialloginapi:v1
    ports:
      - "5093:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

  shoeservice:
    image: socialloginweb:v1
    ports:
      - "5127:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

networks:
  mynetwork:
    # driver: bridge
